version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/home/ben/pgdata/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432

volumes:
  postgres_data: